# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-03 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='renderedText',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
