# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170903_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='bodyText',
            field=models.TextField(blank=True, default="This page doesn't have any content yet."),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='renderedText',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
