# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170903_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='renderedToC',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
